2018-10-01 13:39:59,478 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'firewall_rules']
2018-10-01 13:39:59,488 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'firewall-rules', u'create']
2018-10-01 13:39:59,492 DEBUG    root            Running [gcloud.compute.firewall-rules.create] with arguments: [--allow: "[u'tcp:443']", --description: "JupyterSSH", NAME: "jup-ssh443"]
2018-10-01 13:39:59,497 DEBUG    root            (gcloud.compute.firewall-rules.create) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 848, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 770, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/compute/firewall_rules/create.py", line 113, in Run
    client = holder.client
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/base_classes.py", line 67, in client
    self._client = client_adapter.ClientAdapter(self._api_version)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 58, in __init__
    self._API_NAME, self._api_version, no_http=no_http)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 301, in GetClientInstance
    api_name, api_version, no_http, _CheckResponse, enable_resource_quota)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis_internal.py", line 163, in _GetClientInstance
    response_encoding=encoding, ca_certs=ca_certs)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/http.py", line 71, in Http
    creds = store.LoadIfEnabled()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 282, in LoadIfEnabled
    return Load()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 347, in Load
    raise NoActiveAccountException()
NoActiveAccountException: You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2018-10-01 13:39:59,499 ERROR    root            (gcloud.compute.firewall-rules.create) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
