2018-10-01 13:43:42,490 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'firewall_rules']
2018-10-01 13:43:42,505 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'firewall-rules', u'create']
2018-10-01 13:43:42,513 DEBUG    root            Running [gcloud.compute.firewall-rules.create] with arguments: [--allow: "[u'tcp:443']", --description: "JupyterSSH", NAME: "jup-ssh443"]
2018-10-01 13:43:42,776 INFO     ___FILE_ONLY___ Creating firewall...
2018-10-01 13:46:36,973 DEBUG    root            (gcloud.compute.firewall-rules.create) Aborted by user.
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 848, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 770, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/compute/firewall_rules/create.py", line 120, in Run
    request)])
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 91, in MakeRequests
    progress_tracker=progress_tracker,
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/request_helper.py", line 253, in MakeRequests
    requests=requests, http=http, batch_url=batch_url)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/batch_helper.py", line 106, in MakeRequests
    batch_request_callback=batch_checker.BatchCheck)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 222, in Execute
    batch_http_request.Execute(http)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 494, in Execute
    self.__callback(response, exception)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/batch_helper.py", line 73, in BatchCheck
    is_batch_request=True)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 232, in PromptToEnableApi
    .format(service_token, project)):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/console/console_io.py", line 282, in PromptContinue
    answer = GetAnswer(reprompt)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/console/console_io.py", line 262, in GetAnswer
    answer = _GetInput()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/console/console_io.py", line 106, in _GetInput
    return input()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/console/progress_tracker.py", line 122, in _CtrlCHandler
    raise console_io.OperationCancelledError(self._aborted_message)
OperationCancelledError: Aborted by user.
2018-10-01 13:46:36,975 ERROR    root            (gcloud.compute.firewall-rules.create) Aborted by user.
